-- MySQL Script generated by MySQL Workbench
-- Fri Mar 20 19:33:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Tabel watchlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tabel watchlist` ;

CREATE TABLE IF NOT EXISTS `Tabel watchlist` (
  `id_watchlist` INT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_film` INT NOT NULL,
  `tanggal_tambah` DATETIME NOT NULL,
  PRIMARY KEY (`id_watchlist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tabel comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tabel comments` ;

CREATE TABLE IF NOT EXISTS `Tabel comments` (
  `id_comment` INT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_film` INT NOT NULL,
  `komentar` TEXT NOT NULL,
  `tanggal` DATETIME NOT NULL,
  PRIMARY KEY (`id_comment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tabel history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tabel history` ;

CREATE TABLE IF NOT EXISTS `Tabel history` (
  `id_history` INT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_film` INT NOT NULL,
  `waktu_nonton` DATETIME NOT NULL,
  PRIMARY KEY (`id_history`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tabel user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tabel user` ;

CREATE TABLE IF NOT EXISTS `Tabel user` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `usename` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` VARCHAR(20) NULL,
  `table watchlist_id_watchlist` INT NOT NULL,
  `Tabel watchlist_id_watchlist` INT NOT NULL,
  `Tabel comments_id_comment` INT NOT NULL,
  `Tabel history_id_history` INT NOT NULL,
  PRIMARY KEY (`id_users`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Tabel user_Tabel watchlist_idx` (`Tabel watchlist_id_watchlist` ASC) VISIBLE,
  INDEX `fk_Tabel user_Tabel comments1_idx` (`Tabel comments_id_comment` ASC) VISIBLE,
  INDEX `fk_Tabel user_Tabel history1_idx` (`Tabel history_id_history` ASC) VISIBLE,
  CONSTRAINT `fk_Tabel user_Tabel watchlist`
    FOREIGN KEY (`Tabel watchlist_id_watchlist`)
    REFERENCES `Tabel watchlist` (`id_watchlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tabel user_Tabel comments1`
    FOREIGN KEY (`Tabel comments_id_comment`)
    REFERENCES `Tabel comments` (`id_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tabel user_Tabel history1`
    FOREIGN KEY (`Tabel history_id_history`)
    REFERENCES `Tabel history` (`id_history`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tabel films`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tabel films` ;

CREATE TABLE IF NOT EXISTS `Tabel films` (
  `id_film` INT NOT NULL AUTO_INCREMENT,
  `judul` VARCHAR(45) NOT NULL,
  `deskripsi` TEXT NOT NULL,
  `vidio_url` VARCHAR(255) NOT NULL,
  `vidio_url` VARCHAR(255) NOT NULL,
  `id_admin` INT NOT NULL,
  `Tabel watchlist_id_watchlist` INT NOT NULL,
  `Tabel comments_id_comment` INT NOT NULL,
  `Tabel history_id_history` INT NOT NULL,
  PRIMARY KEY (`id_film`, `id_admin`),
  INDEX `fk_Tabel films_Tabel watchlist1_idx` (`Tabel watchlist_id_watchlist` ASC) VISIBLE,
  INDEX `fk_Tabel films_Tabel comments1_idx` (`Tabel comments_id_comment` ASC) VISIBLE,
  INDEX `fk_Tabel films_Tabel history1_idx` (`Tabel history_id_history` ASC) VISIBLE,
  CONSTRAINT `fk_Tabel films_Tabel watchlist1`
    FOREIGN KEY (`Tabel watchlist_id_watchlist`)
    REFERENCES `Tabel watchlist` (`id_watchlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tabel films_Tabel comments1`
    FOREIGN KEY (`Tabel comments_id_comment`)
    REFERENCES `Tabel comments` (`id_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tabel films_Tabel history1`
    FOREIGN KEY (`Tabel history_id_history`)
    REFERENCES `Tabel history` (`id_history`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
